/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8fafc',
        'surface-dim': '#e2e8f0',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8fafc',
        'surface-container': '#f1f5f9',
        'surface-container-high': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'surface-variant': '#f1f5f9',
        'on-surface': '#0f172a',
        'on-surface-variant': '#64748b',
        'inverse-surface': '#0f172a',
        'inverse-on-surface': '#f8fafc',
        outline: '#cbd5e1',
        'outline-variant': '#e2e8f0',
        'surface-tint': '#4f46e5',

        primary: '#4f46e5',
        'primary-container': '#4338ca',
        'on-primary': '#ffffff',
        'on-primary-container': '#eef2ff',
        'primary-fixed': '#e0e7ff',
        'primary-fixed-dim': '#c7d2fe',
        'on-primary-fixed': '#312e81',
        'on-primary-fixed-variant': '#4338ca',
        'inverse-primary': '#818cf8',

        secondary: '#10b981',
        'secondary-container': '#059669',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#ecfdf5',
        'secondary-fixed': '#d1fae5',
        'secondary-fixed-dim': '#a7f3d0',
        'on-secondary-fixed': '#064e3b',
        'on-secondary-fixed-variant': '#047857',

        tertiary: '#d97706',
        'tertiary-container': '#b45309',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbeb',
        'tertiary-fixed': '#fef3c7',
        'tertiary-fixed-dim': '#fde68a',
        'on-tertiary-fixed': '#78350f',
        'on-tertiary-fixed-variant': '#92400e',

        error: '#ef4444',
        'error-container': '#fee2e2',
        'on-error': '#ffffff',
        'on-error-container': '#991b1b',
      },
      fontFamily: {
        'display-hero': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'sans-serif'],
        'stat-metric': ['Plus Jakarta Sans', 'system-ui', '-apple-system', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'body-base': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'label-badge': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'label-code': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
